name: Publish to gh Packages

on: release

jobs:
  Gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build code, javadoc and publish
        run: ./gradlew clean build javadoc publish
      - name: Upload javadocs as artifact
        run: zip ./build/docs/javadoc
      - uses: actions/upload-artifact@v4
        with:
          name: libJavadoc
          path: build/docs/javadoc.zip
          if-no-files-found: error
          overwrite: true

